# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-24 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_csv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('channel', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=5)),
                ('os', models.CharField(max_length=5)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('installs', models.IntegerField(default=0)),
                ('spend', models.FloatField(default=0)),
                ('revenue', models.FloatField(default=0)),
            ],
        ),
    ]
